engines:
  eslint:
    enabled: true
    channel: "eslint-3"
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
ratings:
  paths:
    - src/**
exclude_paths:
  - src/**/*.test.js
